RETAILER_BUSINESS_NOT_FOUND = "Business not found"
STORE_NOT_FOUND = "Store not found"
HTTP_API_ERROR = 111
HTTP_200_SUCCESS=200
REQUEST_SUCCESSFULL="Successfully Updated!"
CREATED_SUCCESSFULL="Successfully Created!"
MESSAGE="message"
SUCCESS="success"
UNIQUE_STORE_NAME="This store name already exists"
UNIQUE_BUSINESS_NAME="This business name already exists"
UNIQUE_COMPANY_NUMBER="This company number already exists"
UNIQUE_VAT_NUMBER="This VAT number already exists"